name: Create IAM User and Email CSV

on:
  workflow_dispatch:
    inputs:
      iam_username:
        description: 'IAM username to create'
        required: true
      iam_group:
        description: 'IAM group to attach user to'
        required: true
      iam_tags:
        description: 'IAM tags (e.g., Name=John,Department=IT)'
        required: true
      email_to:
        description: 'Email to send CSV to'
        required: true

jobs:
  create-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install boto3
        run: pip install boto3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Create IAM user and send credentials
        run: |
          python create_user_and_email.py \
            "${{ github.event.inputs.iam_username }}" \
            "${{ github.event.inputs.iam_group }}" \
            "${{ github.event.inputs.iam_tags }}" \
            "${{ github.event.inputs.email_to }}" \
            "${{ secrets.SES_VERIFIED_EMAIL }}"
